### PR TITLE
Add "Light (Only Subbar)" theme

### LINKED ISSUE #47: Add a "Light (Only Subbar)" theme
Adding a "Light (Only Subbar)" option to vscode_vibrancy.theme property would be really helpful for working in bright conditions.

### PR DESCRIPTION
**Pull request by Symaxion**
Resolves #47.

### CODE REVIEW

**Comment by rashil2000** [comment]
@Symaxion Great work. 
Couldn't figure it out myself. Glad someone did. 
You might wanna change text colors in the Activity bar and Side bar though, the contrast isn't very good imo. (Testing on Windows 10)

**Comment by Symaxion** [comment]
I think you can change sidebar color as part of your theme, e.g. in settings.json:
```json
    "workbench.colorCustomizations": {
        "activityBar.background": "#FFFFFF",
        "activityBar.border": "#00000011",

        "activityBar.foreground": "#2F7CF6",
        "activityBar.inactiveForeground": "#00000040",
        "activityBarBadge.background": "#00000060",
        "activityBar.activeBorder": "#2F7CF6",

        "sideBar.foreground": "#222222",
        "list.activeSelectionBackground": "#508BEF",
        "list.inactiveSelectionForeground": "#C9D2E3",
        "sideBarSectionHeader.foreground": "#00000060",
        "sideBarSectionHeader.background": "#FFFFFF00",
    },
```

Screenshot 2020-05-11 at 09 29 57

(Edit to your liking)

**Comment by danieloprado** [comment]
image

gorgeous!!!!!! 🎉

My sidebar customization:
```json
{
"workbench.colorCustomizations": {
    "activityBar.activeBorder": "#09A1ED",
    "activityBar.background": "#E7E8E6",
    "activityBar.foreground": "#09A1ED",
    "activityBar.inactiveForeground": "#68696888",
    "activityBarBadge.background": "#09A1ED",
    "list.activeSelectionBackground": "#09A1ED",
    "list.activeSelectionForeground": "#ffffff",
    "list.errorForeground": "#FF5C56",
    "list.focusBackground": "#37a6dd99",
    "list.hoverBackground": "#99999941",
    "list.inactiveSelectionBackground": "#89B5CB33",
    "list.warningForeground": "#B38700",
    "sideBar.background": "#F3F4F5",
    "sideBar.border": "#DEDFE0",
    "sideBar.foreground": "#222222",
    "editorSuggestWidget.background": "#222222e3",
    "editorSuggestWidget.selectedBackground": "#0000003b",
    "input.background": "#E9EAEB",
    "input.foreground": "#222222",
    "input.border": "#E9EAEB",
    "dropdown.border": "#E9EAEB",
    "sideBarSectionHeader.background": "#E9EAEB",
    "sideBarSectionHeader.border": "#DEDFE0",
    "sideBarSectionHeader.foreground": "#000000A0",
    "gitDecoration.untrackedResourceForeground": "#2DAE58",
    "gitDecoration.modifiedResourceForeground": "#00A39F"
  }
}
```

**Comment by rashil2000** [comment]
Hi @EYHN! Could you please look into merging this/adding this? I really love this theme (dark themes at daytime sore my eyes), and currently I have to manually merge this PR locally to use it :(

**Comment by EYHN** [comment]
Thanks to @Symaxion's contribution, I've merged this pr and fixed the contrast of the sidebar icons.



This theme will be added in v1.0.12.

**Pull request merged**
